services:
#  kafka-orders-broker:
#    image: bitnami/kafka:latest
#    container_name: kafka_orders
#    ports:
#      - 9092:9092
#      - 9094:9094
#    environment:
#      KAFKA_NODE_ID: 1
#      KAFKA_CFG_PROCESS_ROLES: broker,controller
#      KAFKA_CFG_LISTENERS: PLAINTEXT://localhost:9092,CONTROLLER://localhost:9093,EXTERNAL://localhost:9094
#      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,EXTERNAL://localhost:9094
#      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
#      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
#      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
#      KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#      KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
#      KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR: 1
#      KAFKA_CFG_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
#      KAFKA_CFG_NUM_PARTITIONS: 3
#      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: true

#  kafka-orders-broker2:
#    image: apache/kafka:latest
#    container_name: kafka_orders_apch
#    ports:
#      - 9092:9092
#      - 9094:9094
#    environment:
#      KAFKA_NODE_ID: 1
#      KAFKA_PROCESS_ROLES: broker,controller
#      KAFKA_LISTENERS: PLAINTEXT://localhost:9092,CONTROLLER://localhost:9093,EXTERNAL://localhost:9094
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,EXTERNAL://localhost:9094
#      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
#      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
#      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
#      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
#      KAFKA_NUM_PARTITIONS: 3
#      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
#    networks:
#      - backend
  kafka2:
    image: apache/kafka:latest
    ports:
      - "9092:9092"
      - 9094:9094
    environment:
      KAFKA_NODE_ID: 0
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://localhost:9092,CONTROLLER://localhost:9093,EXTERNAL://localhost:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,EXTERNAL://localhost:9094
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 0@localhost:9093
      #KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      #KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      #KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      #KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      #KAFKA_NUM_PARTITIONS: 3
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
    networks:
      - backend

networks:
  backend:
    name: b_network
