FROM maven:3.9.9-eclipse-temurin-21 AS builder
LABEL authors="Tonmoy T. Bhattacharya"

WORKDIR /app

COPY pom.xml .

RUN mvn dependency:go-offline -B

COPY src ./src

RUN mvn clean package

FROM eclipse-temurin:21-jdk-jammy AS runner

WORKDIR /app

COPY --from=builder ./app/target/orderfront-0.0.1-SNAPSHOT.jar ./app.jar

EXPOSE 4000

ENTRYPOINT ["java", "-jar", "app.jar"]